### ISSUE TITLE
The dashboard

### ISSUE THREAD

**Issue by Lancelotbronner** [ovh/manager#7790]
### Have you already contacted our help centre?

- [X] Yes, I have contacted the help centre.

### Is there an existing issue for this?

- [X] I have checked the existing issues

### Describe the bug

The dashboard simply never loads, I can't open a ticket with the help center, I can't manage the things I bought, I can't do anything.

I've tried Safari, Chrome, Firefox all on desktop, no difference. I've tried the us and ca subdomains to no avail.

### Steps To Reproduce

1. Go to https://ca.ovh.com/manager/#/web/configuration
2. The loading bar on top makes painfully slow progress for about 15 minutes before millimetres from the end. It stays like that forever (or at least the 1h30 I've waited).
3. See these errors in the developer consoles

```
[Error] undefined is not an object (evaluating 't.replace')
https://ca.ovh.com/auth/signup/new/main.1c7c83cbe504428bcde8.bundle.js:2
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1310424)
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1300951)
	k (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1251499)
	ie (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1300796)
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1294160)
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1293373)
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:190791)
	Pe (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1306513)
	ie (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1301304)
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1294160)
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1293373)
	j (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:195155)
	configUpdated (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:194849)
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:151666)
	forEach
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:151595)
	ut (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:161288)
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:126543)
	forEach
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:126063)
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:137044)
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1344707)
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1344844)
	$digest (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1350207)
	$apply (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1352207)
	T (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1315808)
	M (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1318028)
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1317375)
[Error] Possibly unhandled rejection: {"data":null,"status":-1,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"/engine/apiv6/me","headers":{"Accept":"application/json, text/plain, */*","X-OVH-MANAGER-NAVIGATION-ID":"l6sbq55k","X-OVH-MANAGER-PAGE":"sign-up","X-OVH-MANAGER-REQUEST-ID":"1660420888548-1","Content-Language":"en_GB"},"timeout":{}},"statusText":"","xhrStatus":"error"}
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1310424)
	l (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1344383)
	$digest (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1350207)
	$apply (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1352207)
	T (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1315808)
	M (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1318028)
	_ (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1317441)
[Error] undefined is not an object (evaluating 't.replace')
https://ca.ovh.com/auth/signup/new/main.1c7c83cbe504428bcde8.bundle.js:2
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1310424)
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1300951)
	k (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1251499)
	ie (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1300796)
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1294160)
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1293373)
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:190791)
	Pe (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1306513)
	ie (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1301304)
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1294160)
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1293373)
	j (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:195155)
	configUpdated (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:194849)
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:151666)
	forEach
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:151595)
	ut (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:161288)
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:126543)
	forEach
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:126063)
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:137044)
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1344707)
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1344844)
	$digest (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1350207)
	$apply (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1352207)
	T (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1315808)
	M (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1318028)
	(anonymous function) (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1317375)
```

### Expected Behavior

Access the services I've bought.

### What browsers are you using?

Firefox, Chrome, Safari

### Which devices are used?

Desktop

### Additional information to add?

I'd like to open a ticket with OVH but I can't because the help center just redirects me to the manager.

**Comment by obfuscatedgenerated** [comment]
Also facing the same issue with the error:
```
TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.model (main.4a2be5f809af3cc33ba2.bundle.js:2:259519)
    at n.value (main.4a2be5f809af3cc33ba2.bundle.js:2:260231)
    at vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1300930
    at k (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1251494)
    at ie (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1300794)
    at vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1294158
    at vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1293371
    at Object.<anonymous> (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:190789)
    at vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1257270
    at Pe (vendor.e8741c3be9dd1be6ea7c.bundle.js:2:1306511)
```

**Comment by JeremyDec** [comment]
Hello @Lancelotbronner, @obfuscatedgenerated,

Thanks for your report.

To avoid disclose sensible information here, can you try to reach help center?

This way we will be able to investigate on your cases.

Thanks
Jérémy

**Comment by Lancelotbronner** [comment]
As I've written in my issue:

> I'd like to open a ticket with OVH but I can't because the help center just redirects me to the manager.

**Comment by JeremyDec** [comment]
Can you try with this url: https://help.ovhcloud.com/en/contact-method/? You will be asked to login.

**Comment by 201943376-clg-qc-ca** [comment]
It doesn’t seem to accept my credentials, is there a difference between.ca and .com? Because I’m able to login on .com with the exact same credentials

**Comment by anooparveti** [comment]
Hello @Lancelotbronner, 
Are you still facing this issue?
Thanks!

**Comment by Lancelotbronner** [comment]
I haven't checked in a long time, I'll verify today

**Comment by Lancelotbronner** [comment]
To clarify, which domain are we supposed to use? Being in Canada, I tried `ovh.ca` which redirects to `ovhcloud.com`, then I tried `ca.ovh.com` which leads to the control panel on which my account does not seem to exist. `ovh.com` is the only one which works.

**Comment by anooparveti** [comment]
Hello @Lancelotbronner, 
First of all, sorry for the late response.
`https://ca.ovh.com/manager/` is the correct URL. 
Also, if you're still facing the issue, may I request you to raise an issue on `https://ca.ovh.com/manager/#/dedicated/support/tickets/new`. This would make us track and work on the issue in quick manner and provide you the best possible customer experience.

Thanks!

**Comment by Lancelotbronner** [comment]
Yes I still have the issue, since as I've said multiple times now, my account doesn't appear to exist on ca.ovh.com meaning I cannot open a ticket.

It does work with ovh.com and I'm able to manage my domains but the help center doesn't find my account. Ecen password resets don't work.

**Comment by Lancelotbronner** [comment]
> It can take a site a while to figure out that there's a problem with their 'report a bug' form.

- https://xkcd.com/1163/

**Comment by anooparveti** [comment]
Hello @Lancelotbronner,
Can you please try creating a ticket [here](https://www.ovh.com/manager/#/dedicated/support/tickets/new)?
Thanks!

**Comment by Lancelotbronner** [comment]
Under what category and questions would I create it? I've looked at all of them and none seem particularly fitting..

**Comment by anooparveti** [comment]
Hello @Lancelotbronner,
You can use the following options to create the ticket.
1. Topic -> Incident
2. Product -> Since you're mentioning an issue in Web, I think you can Domain or DNS Zone or Web hosting or any other product you have subscribed 
3. Service concerned -> If you have any service for the selected product, you can choose it or you can check the box "This service is not listed and/or I do not have this service yet"
4. Question -> "Other request"
5. Click "No"
6. Then you will see the form to enter the details. You can enter the information and click "Confirm"

<img width="1071" alt="Screenshot 2023-04-14 at 5 28 18 PM" src="https://user-images.githubusercontent.com/22835814/232038072-d2dc922f-d072-4b3e-8d00-235b9f3ee098.png">
<img width="1419" alt="Screenshot 2023-04-14 at 5 32 07 PM" src="https://user-images.githubusercontent.com/22835814/232038323-19e7965c-f682-432a-8269-b756efafe2ce.png">

Let me know if you're still not able to create a ticket. Thanks!

**Comment by TopGEpitech** [comment]
Same here ovh even with VPN (Singapore, French ) from NordVPN is so painfull , I live in Thailand and I even use asia.ovh and it's so painfull . (No extensions , private navigation through chrome same issues) 
GET https://ovh.slgnt.eu/optiext/eform/bootstrap-datetimepicker/js/locales/bootstrap-datetimepicker.asia.js net::E
RR_ABORTED 404 (Not Found)
survey.dll?ID=dUncjl4Cyg2GMtgFdBhM9BkyVON9C84b8H2dbdoRtoejAU8IHY5iwNQc8r7hEapnpsrU7vUXxS4jB4l8dq&LA…:1 Refused to execute script from 'https://ovh.slgnt.eu/optiext/eform/bootstrap-datetimepicker/js/locales/bootstrap-datetimepicker.asia.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
[Violation] Permissions policy violation: unload is not allowed in this document.


Please employ me I fix it the same day
